# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Training3' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Training3

  target 'Training3Tests' do
    inherit! :search_paths
    pod 'Alamofire', '~> 3.4'
    pod 'Kingfisher', '~> 2.4'
    pod 'R.swift'
    # Pods for testing
  end

  target 'Training3UITests' do
    inherit! :search_paths
    # Pods for testing
    
  end

end
